window.QWEN_EXAMPLE_CATALOG = [
  { language: 'Chinese', audio: 'assets/chinese/random/01.mp3', expectedText: '今天的奶茶很懂事，三分糖，却给了我十分的快乐。' },
  { language: 'English', audio: 'assets/english/random/01.mp3', expectedText: "I tried to make a cup of tea, but the kettle said, 'I'll put you on the list.' Very British, very serious." },
  { language: 'Cantonese', audio: 'assets/cantonese/random/01.mp3', expectedText: '今日個公園好安靜，我慢慢行過條石路。' },
  { language: 'Arabic', audio: 'assets/standard_arabic/random/01.mp3', expectedText: 'قلت سأعود بعد خمس دقائق، فضحكت الساعة وقالت: نعرف هذه القصة.' },
  { language: 'German', audio: 'assets/german/random/01.mp3', expectedText: 'Ich sagte, ich bin in fünf Minuten da; die Uhr hat sehr deutsch gezweifelt.' },
  { language: 'French', audio: 'assets/french/random/01.mp3', expectedText: "J'ai dit que je venais dans cinq minutes; en France, c'est parfois une unité poétique." },
  { language: 'Spanish', audio: 'assets/spanish/random/01.mp3', expectedText: 'Dije que llegaba en cinco minutos, pero eran cinco minutos latinoamericanos, con banda sonora y tráfico.' },
  { language: 'Portuguese', audio: 'assets/portuguese/random/01.mp3', expectedText: 'Eu disse que chegava em cinco minutos; o relógio ouviu e pediu paciência.' },
  { language: 'Indonesian', audio: 'assets/indonesian/random/01.mp3', expectedText: 'Saya bilang lima menit lagi sampai, dan jam langsung pura-pura tidak dengar.' },
  { language: 'Italian', audio: 'assets/italian/random/01.mp3', expectedText: "Ho detto arrivo tra cinque minuti; l'orologio mi ha guardato con gesto italiano." },
  { language: 'Korean', audio: 'assets/korean/random/01.mp3', expectedText: '오 분 뒤에 도착한다고 했더니, 시계가 조용히 웃는 것 같았어요.' },
  { language: 'Russian', audio: 'assets/russian/random/01.mp3', expectedText: 'Я сказал, что приду через пять минут; часы посмотрели на меня с русской грустью.' },
  { language: 'Thai', audio: 'assets/thai/random/01.mp3', expectedText: 'บอกว่าจะถึงในห้านาที แต่นาฬิกาหันมามองเหมือนรู้ความจริงแล้ว' },
  { language: 'Vietnamese', audio: 'assets/vietnamese/random/01.mp3', expectedText: 'Tôi nói năm phút nữa tới, cái đồng hồ nghe xong im lặng rất sâu.' },
  { language: 'Japanese', audio: 'assets/japanese/random/01.mp3', expectedText: '五分で行きますと言ったら、時計が静かに首をかしげました。' },
  { language: 'Turkish', audio: 'assets/turkish/random/01.mp3', expectedText: 'Beş dakikaya geliyorum dedim; saat bana Türk kahvesi falı gibi baktı.' },
  { language: 'Hindi', audio: 'assets/hindi/random/01.mp3', expectedText: 'मैंने कहा पाँच मिनट में आता हूँ, और भारतीय पाँच मिनट ने फिर से इतिहास बना दिया।' },
  { language: 'Malay', audio: 'assets/malay/random/01.mp3', expectedText: 'Pagi tadi jalan masih sunyi dan udara terasa segar.' },
  { language: 'Dutch', audio: 'assets/dutch/random/01.mp3', expectedText: 'Ik zei dat ik er over vijf minuten was; de klok bleef verdacht stil.' },
  { language: 'Swedish', audio: 'assets/swedish/random/01.mp3', expectedText: 'På morgonen var gatan tyst och luften kändes frisk.' },
  { language: 'Danish', audio: 'assets/danish/random/01.mp3', expectedText: 'I morges var gaden stille, og lyset faldt blødt over tagene.' },
  { language: 'Finnish', audio: 'assets/finnish/random/01.mp3', expectedText: 'Aamulla katu oli hiljainen ja ilma tuntui raikkaalta.' },
  { language: 'Polish', audio: 'assets/polish/random/01.mp3', expectedText: 'Powiedziałem, że będę za pięć minut; zegarek tylko spojrzał po polsku i westchnął.' },
  { language: 'Czech', audio: 'assets/czech/random/01.mp3', expectedText: 'Ráno jsem otevřel okno a ulice byla ještě tichá.' },
  { language: 'Filipino', audio: 'assets/filipino/random/01.mp3', expectedText: 'Maaga akong gumising at tahimik pa ang buong kalye.' },
  { language: 'Persian', audio: 'assets/persian/random/01.mp3', expectedText: 'صبح خیابان آرام بود و هوا بوی باران می‌داد.' },
  { language: 'Greek', audio: 'assets/greek/random/01.mp3', expectedText: 'Το πρωί ο δρόμος ήταν ήσυχος και ο αέρας δροσερός.' },
  { language: 'Romanian', audio: 'assets/romanian/random/01.mp3', expectedText: 'Dimineața strada era liniștită și aerul părea proaspăt.' },
  { language: 'Hungarian', audio: 'assets/hungarian/random/01.mp3', expectedText: 'Reggel csendes volt az utca, és friss levegő jött be az ablakon.' },
  { language: 'Macedonian', audio: 'assets/macedonian/random/01.mp3', expectedText: 'Утрото улицата беше тивка и воздухот беше свеж.' },
]
